# 공통 config 파일
# eureka 서버에게 질의하기 위해 필요하며, 모든 모듈에 공통으로 필요
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# port를 0으로 세팅하면 spring이 임의 port를 할당(굳이 8081..등으로 관리할 필요없음)
# eureka에 등록할 때 할당된 임의 port를 알려주고 apigate가 ureka에게 물어보므로 개발자가 port를 관리할 필요가 없다
server:
  port: 0
spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: admin
  jpa:
    #    InnoDB
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
